routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'role:superadmin'])->name('dashboard');

Route::post('dependent-dropdown', 'App\Http\Controllers\Admin\Discussion\DiscusstionController@getTeacherBySchool')
    ->name('dependent-dropdown.index');


Route::group(['middleware' => 'auth'], function () {

    /************************* USER *****************************/
    Route::prefix('user')->group(function () {
        Route::post('/get-quiz-by-school', 'Quiz\QuizController@getQuestionBySchool');
        Route::post('/quiz/submit', 'Quiz\QuizController@submit');
    });
    Route::resource('/order', App\Http\Controllers\Admin\OrderController::class, ['as' => 'admin']);


    /************************* ADMIN *****************************/
    Route::prefix('admin')->group(function () {

        /************************* USER MANAGEMENT *****************************/
        Route::resource('/user', App\Http\Controllers\Admin\UserManagement\UserManagementController::class, ['as' => 'admin']);

        /************************* QUIZ *****************************/
        Route::resource('/quiz', App\Http\Controllers\Admin\Quiz\QuizController::class, ['as' => 'admin']);
        Route::get('show/{id}','App\Http\Controllers\Admin\Discussion\DiscusstionController@showById');

        /************************* DISCUSSION *****************************/
        Route::resource('/discussion', App\Http\Controllers\Admin\Discussion\DiscusstionController::class, ['as' => 'admin']);

    });

    /************************* DATATABLE MANAGEMENT *****************************/
    Route::prefix('datatable')->group(function () {
        Route::get('/user', [App\Http\Controllers\DatatableController::class, 'user']);
    });
});





require __DIR__ . '/auth.php';

app/Http/Controllers/Admin/Discussion/DiscusstionController.php
<?php

namespace App\Http\Controllers\Admin\Discussion;

use App\Http\Controllers\Controller;
use App\Models\Question;
use App\Models\School;
use App\Models\User;
use Illuminate\Http\Request;

class DiscusstionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $discussions = Question::with('school','teacher')->latest()->when(request()->q, function($discussions) {
            $discussions = $products->where('name', 'like', '%'. request()->q . '%');
        })->paginate(10);

        return view('admin.discussion.index',compact('discussions'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $schools = School::latest()->get();
      return view('admin.discussion.create',compact('schools'));
  }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = auth()->user();
        $this->validate($request, [
         'name'          => 'required',
         'level'        => 'required',
         'max_scores'         => 'required'
     ]); 

        $discussion = Question::create([
           'name'          => $request->name,
           'level'          => $request->level,
           'link'          => $request->link,
           'notes'          => $request->notes,
           'max_scores'       => $request->max_scores,
           'school_id'       => auth()->user()->hasRole('superadmin') ?  $request->school_id : auth()->user()->school_id,
           'teacher_id'       => auth()->user()->hasRole('superadmin') ?  $request->teacher_id : auth()->user()->id
       ]);

        if($discussion){
            return redirect()->route('admin.discussion.index')->with(['success' => 'Data Berhasil Disimpan!']);

        }else{

            return redirect()->route('admin.discussion.index')->with(['error' => 'Data Gagal Disimpan!']);

        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function getTeacherBySchool(Request $request)
    {

        $cities = User::whereRoleIs("teacher")->where('school_id', $request->get('id'))
        ->pluck('username', 'id');

        return response()->json($cities);
    }
}

resources/views/admin/discussion/create.blade.php
		@component('layouts.app')


		@section('content')

		@section('section')

		<form action="{{ route('admin.discussion.store') }}" method="POST">
			@csrf
			@if ($errors->any())
			<div class="alert alert-danger" role="alert">
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if (Session::has('success'))
			<div class="alert alert-success text-center">
				<p>{{ Session::get('success') }}</p>
			</div>
			@endif
			

			@if(auth()->user()->hasRole('superadmin'))
			<div class="form-group">
				<label>SEKOLAH</label>
				<select name="school_id" id="school" class="form-control">
					@foreach ($schools as $school)
					<option value="{{ $school->id }}">{{ $school->name }}</option>
					@endforeach
				</select>

				@error('school_id')
				<div class="invalid-feedback" style="display: block">
					{{ $message }}
				</div>
				@enderror
			</div>


			<div class="form-group">
				<label>GURU</label>
				<select name="teacher_id" id="teacher" class="form-control">
					
				</select>

				@error('teacher_id')
				<div class="invalid-feedback" style="display: block">
					{{ $message }}
				</div>
				@enderror
			</div>

			@endif

			<div class="form-group">
				<label>LEVEL</label>
				<select name="level" class="form-control">
					<option value="1">LEVEL 1 </option>
					<option value="2">LEVEL 2 </option>
					<option value="3">LEVEL 3 </option>
					<option value="4">LEVEL 4 </option>
					<option value="5">LEVEL 5 </option>
				</select>

				@error('level')
				<div class="invalid-feedback" style="display: block">
					{{ $message }}
				</div>
				@enderror
			</div>


			<div class="form-group">
				<label >NAMA PEMBAHASAN</label>
				<input type="text" class="form-control" name="name" placeholder="Masukan Pembahasan">
			</div>


			<div class="form-group">
				<label >MAXIMAL SCORE</label>
				<input type="text" class="form-control" name="max_scores" placeholder="Masukan score">
			</div>

			<div class="form-group">
				<label >LINK</label>
				<input type="text" class="form-control" placeholder="(optional)" name="link" >
			</div>


			<div class="form-group">
				<label >NOTES</label>
				<input type="text" class="form-control" placeholder="(optional)" name="notes" >
			</div>

			
			<button type="submit" class="btn btn-outline-success btn-block">Save</button>


		</form>


		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
		<script type="text/javascript">
			$(function () {
				$.ajaxSetup({
					headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') }
				});

				$('#school').on('change', function () {
					axios.post('{{ url("dependent-dropdown") }}', {id: $(this).val()})
					.then(function (response) {
						$('#teacher').empty();

						$.each(response.data, function (id, name) {
							$('#teacher').append(new Option(name, id))
						})
					});
				});
			});
		</script>

		@endsection

		@section('scripts')

		@endsection

		@endsection
		@endcomponent

resources/views/admin/discussion/index.blade.php
@component('layouts.app')


@section('content')

@section('section')

<div class="container-fluid mb-5">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-md-12">
            <div class="card border-0 shadow">
                <div class="card-header">
                    <h6 class="m-0 font-weight-bold"><i class="fa fa-shopping-bag"></i> Discussion</h6>
                </div>

                <div class="card-body">
                    <form action="{{ route('admin.discussion.index') }}" method="GET">
                        <div class="form-group">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <a href="{{ route('admin.discussion.create') }}" class="btn btn-primary btn-sm"
                                    style="padding-top: 10px;"><i class="fa fa-plus-circle"></i> TAMBAH</a>
                                </div>
                                <input type="text" class="form-control" name="q"
                                placeholder="cari berdasarkan pembahasan">
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> CARI
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th scope="col" style="text-align: center;width: 6%">NO.</th>
                                    <th scope="col">PEMBAHASAN</th>
                                    <th scope="col">LEVEL</th>
                                    <th scope="col">LINK</th>
                                    <th scope="col">MAX SCORE</th>
                                    <th scope="col">SEKOLAH</th>
                                    <th scope="col">GURU</th>
                                    <th scope="col" style="width: 15%;text-align: center">AKSI</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($discussions as $no => $quiz)
                                <tr>
                                    <th scope="row" style="text-align: center">
                                        {{ ++$no + ($discussions->currentPage()-1) * $discussions->perPage() }}</th>
                                        <td>{{ $quiz->name }}</td>
                                        <td>{{ $quiz->level }}</td>
                                        <td>{{ $quiz->link }}</td>
                                        <td>{{ $quiz->max_scores }}</td>
                                        <td>{{ $quiz->school->name }}</td>
                                        <td>{{ $quiz->teacher->username }}</td>
                                        <td class="text-center">
                                            <a href="{{ route('admin.discussion.edit', $quiz->id) }}"
                                                class="btn btn-sm btn-primary">
                                                <i class="fa fa-pencil-alt"></i>
                                            </a>

                                            <button onClick="Delete(this.id)" class="btn btn-sm btn-danger"
                                            id="{{ $quiz->id }}">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </td>
                                </tr>

                                @empty

                                <div class="alert alert-danger">
                                    Data Belum Tersedia!
                                </div>

                                @endforelse
                            </tbody>
                        </table>
                        <div style="text-align: center">
                            {{$discussions->links("vendor.pagination.bootstrap-4")}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


@endsection

@section('scripts')

<script>
    function Delete(id) {
        var id = id;
        var token = $("meta[name='csrf-token']").attr("content");

        swal({
            title: "APAKAH KAMU YAKIN ?",
            text: "INGIN MENGHAPUS DATA INI!",
            icon: "warning",
            buttons: [
            'TIDAK',
            'YA'
            ],
            dangerMode: true,
        }).then(function (isConfirm) {
            if (isConfirm) {

                //ajax delete
                jQuery.ajax({
                    url: "{{ route("admin.discussion.index") }}/" + id,
                    data: {
                        "id": id,
                        "_token": token
                    },
                    type: 'DELETE',
                    success: function (response) {
                        if (response.status == "success") {
                            swal({
                                title: 'BERHASIL!',
                                text: 'DATA BERHASIL DIHAPUS!',
                                icon: 'success',
                                timer: 1000,
                                showConfirmButton: false,
                                showCancelButton: false,
                                buttons: false,
                            }).then(function () {
                                location.reload();
                            });
                        } else {
                            swal({
                                title: 'GAGAL!',
                                text: 'DATA GAGAL DIHAPUS!',
                                icon: 'error',
                                timer: 1000,
                                showConfirmButton: false,
                                showCancelButton: false,
                                buttons: false,
                            }).then(function () {
                                location.reload();
                            });
                        }
                    }
                });

            } else {
                return true;
            }
        })
    }

</script>


@endsection

@endsection
@endcomponent