routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'role:superadmin'])->name('dashboard');

Route::post('dependent-dropdown', 'App\Http\Controllers\Admin\Discussion\DiscusstionController@getTeacherBySchool')
    ->name('dependent-dropdown.index');


Route::group(['middleware' => 'auth'], function () {

    /************************* USER *****************************/
    Route::prefix('user')->group(function () {
        Route::post('/get-quiz-by-school', 'Quiz\QuizController@getQuestionBySchool');
        Route::post('/quiz/submit', 'Quiz\QuizController@submit');
    });
    Route::resource('/order', App\Http\Controllers\Admin\OrderController::class, ['as' => 'admin']);


    /************************* ADMIN *****************************/
    Route::prefix('admin')->group(function () {

        /************************* USER MANAGEMENT *****************************/
        Route::resource('/user', App\Http\Controllers\Admin\UserManagement\UserManagementController::class, ['as' => 'admin']);

        /************************* QUIZ *****************************/
        Route::resource('/quiz', App\Http\Controllers\Admin\Quiz\QuizController::class, ['as' => 'admin']);
        Route::get('show/{id}','App\Http\Controllers\Admin\Discussion\DiscusstionController@showById');

        /************************* DISCUSSION *****************************/
        Route::resource('/discussion', App\Http\Controllers\Admin\Discussion\DiscusstionController::class, ['as' => 'admin']);

    });

    /************************* DATATABLE MANAGEMENT *****************************/
    Route::prefix('datatable')->group(function () {
        Route::get('/user', [App\Http\Controllers\DatatableController::class, 'user']);
    });
});





require __DIR__ . '/auth.php';

app/Http/Controllers/Admin/UserManagement/UserManagementController.php
<?php

namespace App\Http\Controllers\Admin\UserManagement;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\School;
use App\Models\Role;
use Illuminate\Http\Request;

class UserManagementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::with('school')->latest()->when(request()->q, function($users) {
            $users = $products->where('username', 'like', '%'. request()->q . '%');
        })->paginate(10);

        return view('admin.user_management.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

     $roles = Role::latest()->get();
     $schools = School::where('status','active')->latest()->get();

     return view('admin.user_management.create',compact('roles','schools'));
 }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

       $this->validate($request, [
           'email'          => 'required|unique:users',
           'username'    => 'required',
           'role_id'        => 'required',
           'school_id'         => 'required',
       ]); 

       $user = User::create([
         'email'          => $request->email,
         'username'          => $request->username,
         'password'           => app('hash')->make('password'),
         'role_id'          => $request->role_id,
         'school_id'       => $request->school_id,
     ]);

       if($user){

        return redirect()->route('admin.user.index')->with(['success' => 'Data Berhasil Disimpan!']);

    }else{

        return redirect()->route('admin.user.index')->with(['error' => 'Data Gagal Disimpan!']);

    }

}

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
     $roles = Role::latest()->get();
     $schools = School::where('status','active')->latest()->get();

     return view('admin.user_management.edit', compact('user','roles','schools'));
 }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, [
           'email'          => 'required|unique:users',
           'username'    => 'required',
           'role_id'        => 'required',
           'school_id'         => 'required',
       ]); 

        $user = User::findOrFail($user->id);
        $user->update([
            'email'          => $request->email,
            'username'          => $request->username,
            'role_id'          => $request->role_id,
            'school_id'       => $request->school_id,
        ]);


        if($user){
            return redirect()->route('admin.user.index')->with(['success' => 'Data Berhasil Diupdate!']);
        }else{
            //redirect dengan pesan error
            return redirect()->route('admin.user.index')->with(['error' => 'Data Gagal Diupdate!']);
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        if($user){
            return response()->json([
                'status' => 'success'
            ]);

        }else{
            return response()->json([
                'status' => 'error'
            ]);


        }

    }
}

resources/views/admin/user_management/create.blade.php
@component('layouts.app')


@section('content')

@section('section')

<form action="{{route('admin.user.store')}}" method="POST">
	@csrf
	@if ($errors->any())
	<div class="alert alert-danger" role="alert">
		<ul>
			@foreach ($errors->all() as $error)
			<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
	@endif
	@if (Session::has('success'))
	<div class="alert alert-success text-center">
		<p>{{ Session::get('success') }}</p>
	</div>
	@endif


	<div class="container-fluid">
		<!-- Page Heading -->
		<div class="row">
			<div class="col-md-12">
				<div class="card border-0 shadow">
					<div class="card-header">
						<h6 class="m-0 font-weight-bold"><i class="fas fa-shopping-bag"></i> TAMBAH USER</h6>
					</div>
					<div class="card-body">
						<form action="{{route('admin.user.store')}}" method="POST" enctype="multipart/form-data">
							@csrf
							<div class="form-group">
								<label>SEKOLAH</label>
								<select name="school_id" class="form-control">
									<option value="">-- PILIH SEKOLAH --</option>
									@foreach ($schools as $school)
									<option value="{{ $school->id }}">{{ $school->name }}</option>
									@endforeach
								</select>

								@error('school_id')
								<div class="invalid-feedback" style="display: block">
									{{ $message }}
								</div>
								@enderror
							</div>


							<div class="form-group">
								<label>ROLE</label>
								<select name="role_id" class="form-control">
									<option value="">-- PILIH ROLE --</option>
									@foreach ($roles as $role)
									<option value="{{ $role->id }}">{{ $role->name }}</option>
									@endforeach
								</select>

								@error('role_id')
								<div class="invalid-feedback" style="display: block">
									{{ $message }}
								</div>
								@enderror
							</div>

							<div class="form-group">
								<label>USERNAME</label>
								<input type="text" name="username" value="{{ old('username') }}" placeholder="Masukkan username"
								class="form-control @error('username') is-invalid @enderror">
								@error('username')
								<div class="invalid-feedback" style="display: block">
									{{ $message }}
								</div>
								@enderror
							</div>

							<div class="form-group">
								<label>EMAIL</label>
								<input type="text" name="email" value="{{ old('email') }}" placeholder="Masukkan email"
								class="form-control @error('email') is-invalid @enderror">
								@error('email')
								<div class="invalid-feedback" style="display: block">
									{{ $message }}
								</div>
								@enderror
							</div>

					
							<div class="badge badge-info">
								password akan terbuat default "password"
							</div>
							<br>

							<br>
							<button class="btn btn-primary mr-1 btn-submit" type="submit"><i class="fa fa-paper-plane"></i>
							SIMPAN</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- /.container-fluid -->


	@endsection

	@section('scripts')

	@endsection

	@endsection
	@endcomponent
	--

resources/views/admin/user_management/edit.blade.php
@component('layouts.app')


@section('content')

@section('section')

<form action="{{route('admin.user.update',$user->id)}}" method="POST">
	@csrf
	@method('PUT')
	@if ($errors->any())
	<div class="alert alert-danger" role="alert">
		<ul>
			@foreach ($errors->all() as $error)
			<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
	@endif
	@if (Session::has('success'))
	<div class="alert alert-success text-center">
		<p>{{ Session::get('success') }}</p>
	</div>
	@endif


	<div class="container-fluid">
		<!-- Page Heading -->
		<div class="row">
			<div class="col-md-12">
				<div class="card border-0 shadow">
					<div class="card-header">
						<h6 class="m-0 font-weight-bold"><i class="fas fa-shopping-bag"></i> TAMBAH USER</h6>
					</div>
					<div class="card-body">
						<form action="{{route('admin.user.update',$user->id)}}" method="POST" enctype="multipart/form-data">
							@csrf
							@method('PUT')	
							<div class="form-group">
								<label>SEKOLAH</label>
								<select name="school_id" class="form-control">
									<option value="">-- PILIH SEKOLAH --</option>
									@foreach ($schools as $school)
									@if($user->school_id == $school->id)
									<option value="{{ $school->id  }}" selected>{{ $school->name }}</option>
									@else
									<option value="{{ $school->id  }}">{{ $school->name }}</option>
									@endif
									@endforeach
								</select>

								@error('school_id')
								<div class="invalid-feedback" style="display: block">
									{{ $message }}
								</div>
								@enderror
							</div>


							<div class="form-group">
								<label>ROLE</label>
								<select name="role_id" class="form-control">
									<option value="">-- PILIH ROLE --</option>
									@foreach ($roles as $role)
									@if($user->role_id == $role->id)
									<option value="{{ $role->id  }}" selected>{{ $role->name }}</option>
									@else
									<option value="{{ $role->id  }}">{{ $role->name }}</option>
									@endif
									@endforeach
								</select>

								@error('role_id')
								<div class="invalid-feedback" style="display: block">
									{{ $message }}
								</div>
								@enderror
							</div>


							<div class="form-group">
								<label>USERNAME</label>
								<input type="text" name="username" value="{{ old('username', $user->username) }}" placeholder="Masukkan username"
								class="form-control @error('username') is-invalid @enderror">
								@error('username')
								<div class="invalid-feedback" style="display: block">
									{{ $message }}
								</div>
								@enderror
							</div>

							<div class="form-group">
								<label>EMAIL</label>
								<input type="text" name="email" value="{{ old('email', $user->email) }}" placeholder="Masukkan email"
								class="form-control @error('email') is-invalid @enderror">
								@error('email')
								<div class="invalid-feedback" style="display: block">
									{{ $message }}
								</div>
								@enderror
							</div>


							<div class="badge badge-info">
								password akan terbuat default "password"
							</div>
							<br>

							<br>
							<button class="btn btn-primary mr-1 btn-submit" type="submit"><i class="fa fa-paper-plane"></i>
							SIMPAN</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- /.container-fluid -->


	@endsection

	@section('scripts')

	@endsection

	@endsection
	@endcomponent
	--

resources/views/admin/user_management/index.blade.php
@component('layouts.app')


@section('content')

@section('section')
<div class="container-fluid mb-5">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-md-12">
            <div class="card border-0 shadow">
                <div class="card-header">
                    <h6 class="m-0 font-weight-bold"><i class="fa fa-shopping-bag"></i> USER</h6>
                </div>

                <div class="card-body">
                    <form action="{{ route('admin.user.index') }}" method="GET">
                        <div class="form-group">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <a href="{{ route('admin.user.create') }}" class="btn btn-primary btn-sm"
                                        style="padding-top: 10px;"><i class="fa fa-plus-circle"></i> TAMBAH</a>
                                </div>
                                <input type="text" class="form-control" name="q"
                                    placeholder="cari berdasarkan username">
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> CARI
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th scope="col" style="text-align: center;width: 6%">NO.</th>
                                    <th scope="col">USERNAME</th>
                                    <th scope="col">EMAIL</th>
                                    <th scope="col">SEKOLAH</th>
                                    <th scope="col" style="width: 15%;text-align: center">AKSI</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($users as $no => $user)
                                <tr>
                                    <th scope="row" style="text-align: center">
                                        {{ ++$no + ($users->currentPage()-1) * $users->perPage() }}</th>
                                    <td>{{ $user->username }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->school->name }}</td>
                                    <td class="text-center">
                                        <a href="{{ route('admin.user.edit', $user->id) }}"
                                            class="btn btn-sm btn-primary">
                                            <i class="fa fa-pencil-alt"></i>
                                        </a>

                                        <button onClick="Delete(this.id)" class="btn btn-sm btn-danger"
                                            id="{{ $user->id }}">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </td>
                                </tr>

                                @empty

                                    <div class="alert alert-danger">
                                        Data Belum Tersedia!
                                    </div>

                                @endforelse
                            </tbody>
                        </table>
                        <div style="text-align: center">
                            {{$users->links("vendor.pagination.bootstrap-4")}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

@endsection

@section('scripts')
<script>
        function Delete(id) {
        var id = id;
        var token = $("meta[name='csrf-token']").attr("content");

        swal({
            title: "APAKAH KAMU YAKIN ?",
            text: "INGIN MENGHAPUS DATA INI!",
            icon: "warning",
            buttons: [
                'TIDAK',
                'YA'
            ],
            dangerMode: true,
        }).then(function (isConfirm) {
            if (isConfirm) {

                //ajax delete
                jQuery.ajax({
                    url: "{{ route("admin.user.index") }}/" + id,
                    data: {
                        "id": id,
                        "_token": token
                    },
                    type: 'DELETE',
                    success: function (response) {
                        if (response.status == "success") {
                            swal({
                                title: 'BERHASIL!',
                                text: 'DATA BERHASIL DIHAPUS!',
                                icon: 'success',
                                timer: 1000,
                                showConfirmButton: false,
                                showCancelButton: false,
                                buttons: false,
                            }).then(function () {
                                location.reload();
                            });
                        } else {
                            swal({
                                title: 'GAGAL!',
                                text: 'DATA GAGAL DIHAPUS!',
                                icon: 'error',
                                timer: 1000,
                                showConfirmButton: false,
                                showCancelButton: false,
                                buttons: false,
                            }).then(function () {
                                location.reload();
                            });
                        }
                    }
                });

            } else {
                return true;
            }
        })
    }

</script>
@endsection

@endsection
@endcomponent