routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'role:superadmin'])->name('dashboard');

Route::post('dependent-dropdown', 'App\Http\Controllers\Admin\Discussion\DiscusstionController@getTeacherBySchool')
    ->name('dependent-dropdown.index');


Route::group(['middleware' => 'auth'], function () {

    /************************* USER *****************************/
    Route::prefix('user')->group(function () {
        Route::post('/get-quiz-by-school', 'Quiz\QuizController@getQuestionBySchool');
        Route::post('/quiz/submit', 'Quiz\QuizController@submit');
    });
    Route::resource('/order', App\Http\Controllers\Admin\OrderController::class, ['as' => 'admin']);


    /************************* ADMIN *****************************/
    Route::prefix('admin')->group(function () {

        /************************* USER MANAGEMENT *****************************/
        Route::resource('/user', App\Http\Controllers\Admin\UserManagement\UserManagementController::class, ['as' => 'admin']);

        /************************* QUIZ *****************************/
        Route::resource('/quiz', App\Http\Controllers\Admin\Quiz\QuizController::class, ['as' => 'admin']);
        Route::get('show/{id}','App\Http\Controllers\Admin\Discussion\DiscusstionController@showById');

        /************************* DISCUSSION *****************************/
        Route::resource('/discussion', App\Http\Controllers\Admin\Discussion\DiscusstionController::class, ['as' => 'admin']);

    });

    /************************* DATATABLE MANAGEMENT *****************************/
    Route::prefix('datatable')->group(function () {
        Route::get('/user', [App\Http\Controllers\DatatableController::class, 'user']);
    });
});





require __DIR__ . '/auth.php';

app/Http/Controllers/Admin/Quiz/QuizController.php
<?php

namespace App\Http\Controllers\Admin\Quiz;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Question;
use App\Models\QuestionDetail;
use App\Models\AnswerDetail;
use DB;

class QuizController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $quizs = Question::with('school','teacher')->latest()->when(request()->q, function($quizs) {
            $quizs = $products->where('name', 'like', '%'. request()->q . '%');
        })->paginate(10);


        return view('admin.quiz.index',compact('quizs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $quiestions = Question::latest()->get();
        return view('admin.quiz.create',compact('quiestions'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $answer = $request->get('answer');
        $isAnswer = $request->get('isTrue'); 
        $arrOutput['answer'] = array();


        $user = auth()->user();
        $this->validate($request, [
           'score'          => 'required|numeric',
           'question_id'        => 'required',
           'question'         => 'required',
       ]); 



        DB::beginTransaction();
        try{
           $questionDetail = QuestionDetail::create([
             'name'          => $request->question,
             'score'          => $request->score,
             'question_id'          => (int) $request->question_id                 
         ]);

           for ($i= 0; $i < count($answer) ; $i++) { 
            if(isset($isAnswer[$i])){
                if($i == $isAnswer[$i]){
                  AnswerDetail::create([
                     'name'          => $answer[$i],
                     'is_answer'          => true,
                     'question_detail_id' => (int) $questionDetail->id                 
                 ]);
              }    
          }else{
              AnswerDetail::create([
                 'name'          => $answer[$i],
                 'is_answer'          => false,
                 'question_detail_id'    => (int)$questionDetail->id                 
             ]);
          }


      }

      DB::commit();
      return redirect()->route('admin.quiz.index')->with(['success' => 'Data Berhasil Disimpan!']);

  } catch (\Exception $th) {
    DB::rollBack();
    return $th;
    return redirect()->route('admin.quiz.index')->with(['error' => $th]);

}

}

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $quiz)
    {
       $questions = Question::latest()->get();
       $question = Question::find($quiz->id)->with('teacher','school','question_detail.answer_detail')->first();
       
       return view('admin.quiz.edit', compact('questions','question'));
   }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    public function showById($id){
        $where = array('id' => $id);
        $customer = Question::where($where)->first();
        return Response::json($customer);
    }
}

app/Http/Controllers/Quiz/QuizController.php
<?php

namespace App\Http\Controllers\Quiz;

use App\Models\Question;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class QuizController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    public function getQuestionBySchool(Request $request)
    {
        $question = Question::where('school_id', $request->school_id)->with('teacher', 'question_detail', 'question_detail.answer_detail')->limit(10)->paginate(1);
        return response()->json([
            'status' => '200',
            'message' => 'OK',
            'data' => $question,
        ], 200);
    }

    public function submit(Request $request)
    {
        try {
            $answer = new Answer();
            $answer->user_id = Auth::id();
            $answer->quiz = $request->input('quiz');
            $answer->scores = $request->input('scores');
            $answer->save();

            return response()->json([
                'status' => '200',
                'message' => 'OK',
                'data' => $answer,

            ], 200);
        } catch (\Exception $e) {
            return $e;
            return response()->json([
                'status' => 503,
                'message' => 'FAILED',
                'error' => $e
            ], 503);
        }
    }
}

resources/views/admin/quiz/create.blade.php
		@component('layouts.app')


		@section('content')

		@section('section')

		<form action="{{ route('admin.quiz.store') }}" method="POST">
			@csrf
			@if ($errors->any())
			<div class="alert alert-danger" role="alert">
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if (Session::has('success'))
			<div class="alert alert-success text-center">
				<p>{{ Session::get('success') }}</p>
			</div>
			@endif
			<div class="form-group">
				<label>PEMBAHASAN</label>
				<select name="question_id" class="form-control">
					<option value="">-- PILIH PEMBAHASAN --</option>
					@foreach ($quiestions as $school)
					<option value="{{ $school->id }}">{{ $school->name }} - {{ $school->max_scores }} max scores</option>
					@endforeach
				</select>

				@error('question_id')
				<div class="invalid-feedback" style="display: block">
					{{ $message }}
				</div>
				@enderror
			</div>

			<div class="form-group">
				<label >Score</label>
				<input type="text" class="form-control" name="score" placeholder="Masukan score">
			</div>

			<table class="table table-bordered" id="dynamicAddRemove">
				<thead>
					<tr>
						<th scope="col"><input type="text" name="question" placeholder="masukan pertanyaan" class="form-control" /></th>
						<th scope="col"><center>Jawaban benar?</center></th>
						<th scope="col"><center><button type="button" name="add" id="dynamic-ar" class="btn btn-outline-primary addRow">+ Jawaban</button></center></th>
					</tr>
				</thead>

				<tbody>
					<tr>
					</tr>
				</tbody>
			</table>
			<button type="submit" class="btn btn-outline-success btn-block">Save</button>


		</form>


		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>

		<script type="text/javascript">
			var i = 0;
			$("#dynamic-ar").click(function () {
				if(i <6){
					$("#dynamicAddRemove").append(`<tr>
						<td>
						<input type="text" name="answer[${i}]" class="form-control qty" >
						</td>
						<td>
						<input type="checkbox" name="isTrue[${i}]" value ="${i}" class="form-control">
						</td>
						<td>
						<center>
						<button type="button" class="btn btn-outline-danger remove-input-field">Delete</button>
						</center>
						</td>
						</tr>`
						);	
				}

				i++;
			});
			

			$(document).on('click', '.remove-input-field', function () {
							// $(this).parents('tr').remove();
							var l =$('tbody tr').length;
							if(l==1){
								alert('you cant delete last one')
							}else{
								$(this).parents('tr').remove();
							}
						});
					</script>

					@endsection

					@section('scripts')

					@endsection

					@endsection
					@endcomponent

resources/views/admin/quiz/edit.blade.php
		@component('layouts.app')


		@section('content')

		@section('section')

		<form action="{{ route('admin.quiz.store') }}" method="POST">
			@csrf
			@if ($errors->any())
			<div class="alert alert-danger" role="alert">
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if (Session::has('success'))
			<div class="alert alert-success text-center">
				<p>{{ Session::get('success') }}</p>
			</div>
			@endif
			
			<div class="form-group">
				<label>PEMBAHASAN</label>
				<select name="question_id" class="form-control">
					<option value="">-- PILIH PEMBAHASAN --</option>
					@foreach ($questions as $quiz)
					@if($question->id == $quiz->id)
					<option value="{{ $quiz->id  }}" selected>{{ $quiz->name }}</option>
					@else
					<option value="{{ $quiz->id  }}">{{ $quiz->name }}</option>
					@endif
					@endforeach
				</select>

				@error('question_id')
				<div class="invalid-feedback" style="display: block">
					{{ $message }}
				</div>
				@enderror
			</div>


			<div class="form-group">
				<label>MAX SCORE</label>
				<input type="text" name="score" value="{{ old('max_scores', $quiz->max_scores) }}" placeholder="Masukkan max_scores"
				class="form-control @error('max_scores') is-invalid @enderror">
				@error('max_scores')
				<div class="invalid-feedback" style="display: block">
					{{ $message }}
				</div>
				@enderror
			</div>

			@foreach ($question->question_detail as $key=>$detail)
			<table class="table table-bordered" id="dynamicAddRemove">
				<thead>
					<tr>
						<th scope="col">

							<div class="row">

								<div class="col-1">
									<center>	{{$key +1}}
									</center>	
								</div>
								
								<div class="col">
									<input type="text" name="question" value="{{ old('detail->name', $detail->name) }}" placeholder="masukan pertanyaan" class="form-control @error('detail->name') is-invalid @enderror" readonly />
									@error('max_scores')
									<div class="invalid-feedback" style="display: block">
										{{ $message }}
									</div>
									@enderror

								</div>					
							</div>
						</th>

						<th scope="col"><center>
							Jawaban
						</center></th>
						<th>
							<center>				
								<div class="btn-group" role="group" aria-label="Button group with nested dropdown">
									<button type="button" class="btn btn-danger">Hapus</button>
									<a class="btn btn-info show-edit" href="javascript:void(0)" id="edit-question" data-toggle="modal" data-id="{{ $detail->id }}">Edit</a>
								</div></center>							
							</th>
						</tr>


						@foreach ($detail->answer_detail as $answer)

						<tr>
							<td>
								<div class="row">

									<div class="col">
										<ul>
											<li>				
												<input type="text" value="{{$answer->name}}" name="answer[{{$answer->id}}]" class="form-control qty" ></li>
											</ul>
										</div>					
									</div>
								</td>
								<td>
									<center>
										<input name="isTrue[${i}]" type="checkbox" class="form-check-input" value="" {{ ($answer->is_answer != "0" ? 'checked' : '')}}>

									</center>
								</td>
								<td>							
									<center>
										<a href=""
										class="btn btn-sm btn-info">
										<i class="fa fa-pencil-alt"></i>
									</a>

								</center>
							</td>
						</tr>
						@endforeach

					</thead>

					<tbody>
						<tr>
						</tr>
					</tbody>
				</table>
				@endforeach



			</form>
			<!-- Show customer modal -->
			<div class="modal fade" id="crud-modal-show" aria-hidden="true" >
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<h4 class="modal-title" id="customerCrudModal-show"></h4>
						</div>
						<div class="modal-body">
							<div class="row">
								<div class="col-xs-2 col-sm-2 col-md-2"></div>
								<div class="col-xs-10 col-sm-10 col-md-10 ">
									@if(isset($customer->name))

									<table>
										<tr><td><strong>Name:</strong></td><td>{{$customer->name}}</td></tr>
										<tr><td><strong>Email:</strong></td><td>{{$customer->email}}</td></tr>
										<tr><td><strong>Address:</strong></td><td>{{$customer->address}}</td></tr>
										<tr><td colspan="2" style="text-align: right "><a href="{{ route('customers.index') }}" class="btn btn-danger">OK</a> </td></tr>
									</table>
									@endif
								</div>
							</div>
						</div>
					</div>
				</div>	
			</div>


			<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
			<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>

			<script type="text/javascript">

				$(document).ready(function() {
					$(".show-edit").on("click",function() {
						var customer_id = $(this).data('id');
						$.get({{url("admin/show/" )}} + customer_id, function (data) {
							$('#customerCrudModal').html("Edit customer");
							$('#btn-update').val("Update");
							$('#btn-save').prop('disabled',false);
							$('#crud-modal').modal('show');
							$('#cust_id').val(data.id);
							$('#name').val(data.name);
							$('#email').val(data.email);
							$('#address').val(data.address);
						})
					});


					var i = 0;
					$("#dynamic-ar").click(function () {
						if(i <6){
							$("#dynamicAddRemove").append(`<tr>
								<td>
								<input type="text" name="answer[${i}]" class="form-control qty" >
								</td>
								<td>
								<input type="checkbox" name="isTrue[${i}]" value ="${i}" class="form-control">
								</td>
								<td>
								<center>
								<button type="button" class="btn btn-outline-danger remove-input-field">Delete</button>
								</center>
								</td>
								</tr>`
								);	
						}

						i++;
					});


					$(document).on('click', '.remove-input-field', function () {
							// $(this).parents('tr').remove();
							var l =$('tbody tr').length;
							if(l==1){
								alert('you cant delete last one')
							}else{
								$(this).parents('tr').remove();
							}
						});
				});
				function category_manage(id, payload) {
					alert(id);
				}
			</script>

			@endsection

			@section('scripts')

			@endsection

			@endsection
			@endcomponent

resources/views/admin/quiz/index.blade.php
@component('layouts.app')


@section('content')

@section('section')

<div class="container-fluid mb-5">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-md-12">
            <div class="card border-0 shadow">
                <div class="card-header">
                    <h6 class="m-0 font-weight-bold"><i class="fa fa-shopping-bag"></i> Quiz</h6>
                </div>

                <div class="card-body">
                    <form action="{{ route('admin.quiz.index') }}" method="GET">
                        <div class="form-group">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <a href="{{ route('admin.quiz.create') }}" class="btn btn-primary btn-sm"
                                    style="padding-top: 10px;"><i class="fa fa-plus-circle"></i> TAMBAH</a>
                                </div>
                                <input type="text" class="form-control" name="q"
                                placeholder="cari berdasarkan pembahasan">
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> CARI
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th scope="col" style="text-align: center;width: 6%">NO.</th>
                                    <th scope="col">PEMBAHASAN</th>
                                    <th scope="col">LEVEL</th>
                                    <th scope="col">LINK</th>
                                    <th scope="col">MAX SCORE</th>
                                    <th scope="col">SEKOLAH</th>
                                    <th scope="col">GURU</th>
                                    <th scope="col" style="width: 15%;text-align: center">AKSI</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($quizs as $no => $quiz)
                                <tr>
                                    <th scope="row" style="text-align: center">
                                        {{ ++$no + ($quizs->currentPage()-1) * $quizs->perPage() }}</th>
                                        <td>{{ $quiz->name }}</td>
                                        <td>{{ $quiz->level }}</td>
                                        <td>{{ $quiz->link }}</td>
                                        <td>{{ $quiz->max_scores }}</td>
                                        <td>{{ $quiz->school->name }}</td>
                                        <td>{{ $quiz->teacher->username }}</td>
                                        <td class="text-center">
                                            <a href="{{ route('admin.quiz.edit', $quiz->id) }}"
                                                class="btn btn-sm btn-primary">
                                                <i class="fa fa-pencil-alt"></i>
                                            </a>

                                            <button onClick="Delete(this.id)" class="btn btn-sm btn-danger"
                                            id="{{ $quiz->id }}">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </td>
                                </tr>

                                @empty

                                <div class="alert alert-danger">
                                    Data Belum Tersedia!
                                </div>

                                @endforelse
                            </tbody>
                        </table>
                        <div style="text-align: center">
                            {{$quizs->links("vendor.pagination.bootstrap-4")}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


@endsection

@section('scripts')

<script>
    function Delete(id) {
        var id = id;
        var token = $("meta[name='csrf-token']").attr("content");

        swal({
            title: "APAKAH KAMU YAKIN ?",
            text: "INGIN MENGHAPUS DATA INI!",
            icon: "warning",
            buttons: [
            'TIDAK',
            'YA'
            ],
            dangerMode: true,
        }).then(function (isConfirm) {
            if (isConfirm) {

                //ajax delete
                jQuery.ajax({
                    url: "{{ route("admin.quiz.index") }}/" + id,
                    data: {
                        "id": id,
                        "_token": token
                    },
                    type: 'DELETE',
                    success: function (response) {
                        if (response.status == "success") {
                            swal({
                                title: 'BERHASIL!',
                                text: 'DATA BERHASIL DIHAPUS!',
                                icon: 'success',
                                timer: 1000,
                                showConfirmButton: false,
                                showCancelButton: false,
                                buttons: false,
                            }).then(function () {
                                location.reload();
                            });
                        } else {
                            swal({
                                title: 'GAGAL!',
                                text: 'DATA GAGAL DIHAPUS!',
                                icon: 'error',
                                timer: 1000,
                                showConfirmButton: false,
                                showCancelButton: false,
                                buttons: false,
                            }).then(function () {
                                location.reload();
                            });
                        }
                    }
                });

            } else {
                return true;
            }
        })
    }

</script>


@endsection

@endsection
@endcomponent